name: üöÄ Pipeline testing

on: page_build

jobs:
  regression-test:
    name: ü§ñ Regression testing
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  wopee:
    name: üêí Wopee bot testing
    needs: regression-test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Get last package version
        run: gh release download --repo autonomous-testing/bot-mvp --archive zip --dir dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_30D_EXPIRATION }} # Set new PAT when expires https://github.com/settings/tokens

      - name: Install wopee
        run: |
          pip install dist/*.zip
          playwright install

      - name: Run wopee tests
        run: |
          sed -i 's/neo4j_password: get.from.sercets/neo4j_password: ${{ secrets.NEO4J_PSWD }}/g' wopee/dronjo.cloud.yaml
          bot_mvp wopee/dronjo.cloud.yaml
        env:
          VRT_API_KEY: ${{ secrets.VRT_API_KEY }}

      - name: Collect logs
        run: |
          mkdir logs
          mv bot.errors.log logs
          mv bot.log logs

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: wopee-logs
          path: logs/
          retention-days: 30

  regression-w-assitant:
    name: üèãÔ∏è Wopee assistant testing
    needs: regression-test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run assistant
        env:
          VRT_API_KEY: ${{ secrets.VRT_API_KEY }}

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
